### ISSUE TITLE
Possible error in the algorithm as shown on the README

### ISSUE THREAD

**Issue by tdeboissiere** [bckenstler/CLR#2]
Shouldn't the update rule be:

`lr = base_lr + (max_lr - base_lr) * ....`

rather than 

`lr = base_lr + (max_lr - lr) * ...`

Otherwise you don't get the linear relationship.

**Comment by bckenstler** [comment]
You are absolutely right, and that's how it is actually implemented. I only wrote it wrong in the example on the README, thanks for pointing out!
