### ISSUE TITLE
FYI - Trapezoid schedule implementation is ready

### ISSUE THREAD

**Issue by daisukelab** [bckenstler/CLR#6]
Thanks to your CLR implementation, I forked and tailored another version for trapezoid schedule which is introduced in this paper:
- [Chen Xing, Devansh Arpit, Christos Tsirigotis, Yoshua Bengio,
   A Walk with SGD, arXiv:1802.08770](https://arxiv.org/abs/1802.08770).

This is just for your information, you can find it here: https://github.com/daisukelab/TrapezoidalLR

I was thinking I could ask for merge, but I just kept it as another version. I guess the trapezoid schedule might be a temporary solution though I implemented...

**Comment by chumingqian** [comment]
Hello, @daisukelab :
     According to your repository description, the learning rate increases from base_lr to max_lr. Should the order of base_lr and max_lr be swapped in the image?

**Comment by daisukelab** [comment]
Hi @chumingqian 
Thanks for your comment. You are probably correct, though I cannot be sure because it is very old work.
I simply replaced max_lr and base_lr.
Thanks again, (and closing this issue... after leaving for 6 years.)
